# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('ra', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=80)),
                ('celular', models.CharField(max_length=11)),
                ('sigla_curso', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Alunos',
                'verbose_name': 'Aluno',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(default='', max_length=10)),
                ('nome', models.CharField(max_length=200)),
                ('matutino', models.BooleanField(default=False)),
                ('vespertino', models.BooleanField(default=False)),
                ('noturno', models.BooleanField(default=False)),
                ('integral', models.BooleanField(default=False)),
                ('modalidade', models.CharField(max_length=200)),
                ('duracao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id_grade', models.AutoField(primary_key=True, serialize=False)),
                ('sigla_curso', models.CharField(max_length=5, unique=True)),
                ('ano', models.SmallIntegerField(unique=True)),
                ('semestre', models.CharField(max_length=1, unique=True)),
            ],
        ),
    ]
