# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 00:01
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivosQuestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=core.models.monta_arquivo_questao)),
            ],
        ),
        migrations.CreateModel(
            name='ArquivosResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=core.models.monta_arquivo_resposta)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CursoTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=240, unique=True)),
                ('carga_horaria', models.IntegerField()),
                ('teoria', models.DecimalField(decimal_places=3, max_digits=3)),
                ('pratica', models.DecimalField(decimal_places=3, max_digits=3)),
                ('ementa', models.TextField()),
                ('competencias', models.TextField()),
                ('habilidades', models.TextField()),
                ('conteudo', models.TextField()),
                ('bibliografia_basica', models.TextField()),
                ('bibliografica_complementar', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('semestre', models.CharField(max_length=1)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('semestre', models.CharField(max_length=1)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
            options={
                'verbose_name': 'Grade Curricular',
                'verbose_name_plural': 'Grades Curriculares',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('grade_curricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GradeCurricular')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('data_limite_entrega', models.DateField()),
                ('descricao', models.TextField()),
                ('data', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField()),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('avaliacao', models.TextField()),
                ('descricao', models.TextField()),
                ('data_de_envio', models.DateField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.Aluno')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Questao')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_turma', models.CharField(max_length=1)),
                ('turno', models.CharField(max_length=15)),
                ('disciplina_ofertada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DisciplinaOfertada')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.Professor')),
            ],
        ),
        migrations.AddField(
            model_name='questao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together=set([('sigla', 'nome')]),
        ),
        migrations.AddField(
            model_name='arquivosresposta',
            name='resposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Resposta'),
        ),
        migrations.AddField(
            model_name='arquivosquestao',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Questao'),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together=set([('disciplina_ofertada', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='resposta',
            unique_together=set([('questao', 'aluno')]),
        ),
        migrations.AlterUniqueTogether(
            name='questao',
            unique_together=set([('turma', 'numero')]),
        ),
        migrations.AlterUniqueTogether(
            name='periododisciplina',
            unique_together=set([('periodo', 'disciplina')]),
        ),
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together=set([('grade_curricular', 'numero')]),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=set([('aluno', 'turma')]),
        ),
        migrations.AlterUniqueTogether(
            name='gradecurricular',
            unique_together=set([('curso', 'ano', 'semestre')]),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinaofertada',
            unique_together=set([('disciplina', 'ano', 'semestre')]),
        ),
        migrations.AlterUniqueTogether(
            name='cursoturma',
            unique_together=set([('curso', 'turma')]),
        ),
        migrations.AlterUniqueTogether(
            name='arquivosresposta',
            unique_together=set([('resposta', 'arquivo')]),
        ),
        migrations.AlterUniqueTogether(
            name='arquivosquestao',
            unique_together=set([('questao', 'arquivo')]),
        ),
    ]
