# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('ra', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=80)),
                ('celular', models.CharField(max_length=11)),
                ('sigla_curso', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(default='', max_length=10)),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=240, unique=True)),
                ('carga_horaria', models.IntegerField()),
                ('teoria', models.DecimalField(decimal_places=3, max_digits=3)),
                ('pratica', models.DecimalField(decimal_places=3, max_digits=3)),
                ('ementa', models.TextField()),
                ('competencias', models.TextField()),
                ('habilidades', models.TextField()),
                ('conteudo', models.TextField()),
                ('bibliografia_basica', models.TextField()),
                ('bibliografica_complementar', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id_disciplina_ofertada', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField(unique=True)),
                ('semestre', models.CharField(max_length=1, unique=True)),
                ('nome_disciplina', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(unique=True)),
                ('semestre', models.CharField(max_length=1, unique=True)),
                ('curso', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
            options={
                'verbose_name': 'Grade Curricular',
                'verbose_name_plural': 'Grades Curriculares',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('cursos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('turno', models.CharField(max_length=15)),
                ('ano_ofertado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.DisciplinaOfertada')),
                ('nome_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina')),
            ],
        ),
    ]
