# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(default='', max_length=10)),
                ('nome', models.CharField(max_length=200)),
                ('matutino', models.BooleanField(default=False)),
                ('vespertino', models.BooleanField(default=False)),
                ('noturno', models.BooleanField(default=False)),
                ('integral', models.BooleanField(default=False)),
                ('modalidade', models.CharField(max_length=200)),
                ('duracao', models.CharField(max_length=200)),
            ],
        ),
    ]
