# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='pratica',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='teoria',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
