# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171116_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(default='', max_length=10)),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
