# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171114_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id_grade', models.AutoField(primary_key=True, serialize=False)),
                ('sigla_curso', models.CharField(max_length=5, unique=True)),
                ('ano', models.SmallIntegerField(unique=True)),
                ('semestre', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='alunos',
            name='email',
            field=models.EmailField(max_length=80),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='ra',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
