# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id_disciplina_ofertada', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.SmallIntegerField(unique=True)),
                ('semestre', models.CharField(max_length=1, unique=True)),
                ('fk_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina')),
            ],
        ),
    ]
