# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171116_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('curso', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
        ),
        migrations.AlterModelOptions(
            name='gradecurricular',
            options={'verbose_name': 'Grade Curricular', 'verbose_name_plural': 'Grades Curriculares'},
        ),
        migrations.RemoveField(
            model_name='gradecurricular',
            name='id_grade',
        ),
        migrations.RemoveField(
            model_name='gradecurricular',
            name='sigla_curso',
        ),
        migrations.AddField(
            model_name='gradecurricular',
            name='curso',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.Curso'),
        ),
        migrations.AddField(
            model_name='gradecurricular',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gradecurricular',
            name='ano',
            field=models.IntegerField(unique=True),
        ),
    ]
