# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_disciplinaofertada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('turno', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='disciplinaofertada',
            name='fk_disciplina',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(default=True, max_length=240, unique=True),
        ),
        migrations.AddField(
            model_name='disciplinaofertada',
            name='nome_disciplina',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina'),
        ),
        migrations.AlterField(
            model_name='disciplinaofertada',
            name='ano',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='ano_ofertado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.DisciplinaOfertada'),
        ),
        migrations.AddField(
            model_name='turma',
            name='nome_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina'),
        ),
    ]
