# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171121_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='curso',
            new_name='cursos',
        ),
    ]
