# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 18:40
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group

def load_groups(apps, schema_editor):
    coordenadores = Group(id=1, name='Coordenadores')
    coordenadores.save()

    alunos = Group(id=2, name='Alunos')
    alunos.save()

    professores = Group(id=3, name='Professores')
    professores.save()

def delete_groups(apps, schema_editor):
    Group.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial')
    ]

    operations = [
        migrations.RunPython(load_groups, delete_groups),
    ]
