# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20171122_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='usuario_id',
        ),
    ]
