# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20171127_1409'),
        ('core', '0003_auto_20171127_1409'),
        ('admin', '0002_logentry_remove_auto_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
